allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven {
            url 'https://gitlab.com/api/v4/groups/124995410/-/packages/maven'
            credentials {
                username = "gitlab+deploy-token-12503766"
                password = "gldt-LCLRzdWKmqALg_qCHaNK" // or CI_JOB_TOKEN
            }
        }
           /* maven {
                url 'https://storage.googleapis.com/download.flutter.io'
            }*/
        }
    }


/*buildscript {
    ext.kotlin_version = '1.8.22'   // make sure this matches a stable Kotlin version
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        //classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0'
    }
}*/

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

/*dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        //mavenLocal()
        *//*google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }*//*
        maven {
            url 'https://gitlab.com/api/v4/groups/124995410/-/packages/maven'
            credentials {
                username = "gitlab+deploy-token-12503766"
                password = "gldt-LCLRzdWKmqALg_qCHaNK" // or CI_JOB_TOKEN
            }
        }
       *//* maven {
            url 'https://storage.googleapis.com/download.flutter.io'
        }*//*

    }
}*/
