allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven {
            url 'https://gitlab.com/api/v4/groups/{PROJECT_ID}/-/packages/maven'
            credentials {
                username = "gitlab-username"
                password = "gldt-sameple_token"
            }
        }
           /* maven {
                url 'https://storage.googleapis.com/download.flutter.io'
            }*/
        }
    }


rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

